# Generated by Django 3.1.3 on 2020-12-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20201203_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='contactus',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
